---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: :verify_peer
  data_bags_path: test/integration/default/data_bags
  nodes_path: test/integration/default/nodes
  attributes:
    tz: 'America/Los_Angeles'
    authorization:
      sudo:
        users: [vagrant]
        passwordless: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[otr::default]

  - name: deployment
    driver:
      network:
        - ["private_network", {ip: "10.10.10.100"}]
    run_list:
      - recipe[otr::deployment]
    attributes:
      otr:
        deployments:
          - name: default

  - name: mysql-server
    driver:
      network:
        - ["private_network", {ip: "10.10.10.101"}]
    run_list:
      - recipe[otr::mysql_server]
    attributes:
      mysql:
        server_root_password: password
      otr:
        mysql_sudoroot_password: password
        mysql_admin: true

  - name: lamp-app
    driver:
      network:
        - ["private_network", {ip: "10.10.10.102"}]
    run_list:
      - recipe[otr::lamp_app_server]
      - recipe[otr::deployment]
    attributes:
      otr:
        services:
          - name: default
        apps:
          - name: default_app
            type: lamp
            moniker: app
            service: default
        deployments:
          - name: app_default
            apps: [{type: "lamp", name: "default_app"}]

  - name: static-app
    driver:
      network:
        - ["private_network", {ip: "10.10.10.103"}]
    run_list:
      - recipe[otr::static_app_server]
      - recipe[otr::deployment]
    attributes:
      otr:
        services:
          - name: default
        apps:
          - name: default_assets
            type: static
            moniker: assets
            service: default
        deployments:
          - name: app_default
            apps: [{type: "static", name: "default_assets"}]
