---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: :verify_peer
  data_bags_path: test/integration/default/data_bags
  nodes_path: test/integration/default/nodes
  attributes:
    tz: 'America/Los_Angeles'
    authorization:
      sudo:
        users: [vagrant]
        passwordless: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[core::default]

  - name: deployment
    run_list:
      - recipe[core::deployment]
    attributes:
      core:
        deployments:
          app_default: {}

  - name: storage-server
    driver:
      network:
        - ["private_network", {ip: "10.10.10.100"}]
    run_list:
      - recipe[core::storage_server]
    attributes:
      core:
        storage:
          default_app: {}

  - name: mysql-server
    driver:
      network:
        - ["private_network", {ip: "10.10.10.101"}]
    run_list:
      - recipe[core::mysql_server]
    attributes:
      mysql:
        server_root_password: password
      core:
        mysql_sudoroot_password: password
        mysql_admin: true

  - name: lamp-app
    driver:
      network:
        - ["private_network", {ip: "10.10.10.102"}]
    run_list:
      - recipe[core::lamp_app_server]
      - recipe[core::deployment]
    attributes:
      core:
        services:
          default: {}
        storage_access:
          default_app:
            writeable: true
        apps:
          default_app:
            type: lamp
            moniker: app
            service: default
            database: true
        deployments:
          app_default:
            apps: [{type: "lamp", name: "default_app"}]

  - name: static-app
    driver:
      network:
        - ["private_network", {ip: "10.10.10.103"}]
    run_list:
      - recipe[core::static_app_server]
      - recipe[core::deployment]
    attributes:
      core:
        services:
          default: {}
        storage_access:
          default_app: {}
        apps:
          default_assets:
            type: static
            moniker: assets
            service: default
        deployments:
          app_default:
            apps: [{type: "static", name: "default_assets"}]
