---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: :verify_peer
  data_bags_path: test/integration/default/data_bags
  attributes:
    tz: 'America/Los_Angeles'
    authorization:
      sudo:
        users: [vagrant]
        passwordless: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[otr::default]

  - name: deployment
    run_list:
      - recipe[otr::deployment]
