---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: :verify_peer
  data_bags_path: test/integration/default/data_bags
  attributes:
    tz: 'America/Los_Angeles'
    authorization:
      sudo:
        users: [vagrant]
        passwordless: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[otr::default]

  - name: deployment
    driver:
      network:
        - ["private_network", {ip: "10.10.10.100"}]
        - ["forwarded_port", {guest: 20, host: 2201}]
    run_list:
      - recipe[otr::deployment]

  - name: mysql-server
    driver:
      network:
        - ["private_network", {ip: "10.10.10.101"}]
        - ["forwarded_port", {guest: 80, host: 8181}]
        - ["forwarded_port", {guest: 443, host: 4431}]
    run_list:
      - recipe[otr::mysql_server]
    attributes:
      mysql:
        server_root_password: password
      otr:
        mysql_admin: true

  - name: lamp-app
    driver:
      network:
        - ["private_network", {ip: "10.10.10.102"}]
        - ["forwarded_port", {guest: 80, host: 8182}]
        - ["forwarded_port", {guest: 443, host: 4432}]
    run_list:
      - recipe[otr::lamp_app_server]
