#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant
  require_chef_omnibus: 12.3.0

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  data_bags_path: test/integration/default/data_bags
  nodes_path: test/integration/default/nodes
  attributes:
    authorization:
      sudo:
        passwordless: true
        users: [vagrant]
    tz: 'America/Los_Angeles'

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[core::default]
      - recipe[core::firewall]

  - name: deployment
    run_list:
      - recipe[core::deployment]
      - recipe[core::firewall]
    attributes:
      core:
        deployments:
          app_default: {}

  - name: storage-server
    driver:
      network:
        - ["private_network", {ip: "10.10.10.100"}]
    run_list:
      - recipe[core::storage_server]
      - recipe[core::firewall]
    attributes:
      core:
        storage:
          default_app_uploads:
            enabled: true

  - name: mysql-server
    driver:
      network:
        - ["private_network", {ip: "10.10.10.101"}]
    run_list:
      - recipe[core::mysql_server]
      - recipe[core::firewall]
    attributes:
      core:
        mysql:
          admin: true
          root_password: password
          sudoroot_password: password

  - name: lamp-app
    driver:
      network:
        - ["private_network", {ip: "10.10.10.102"}]
    run_list:
      - recipe[core::lamp_app_server]
      - recipe[core::deployment]
      - recipe[core::firewall]
    attributes:
      core:
        apps:
          default_app:
            type: lamp
            moniker: app
            service: default
            shared: ["cache"]
            storage:
              default_app_uploads:
                path: uploads
                options: rw
            database: true
        deployments:
          app_default:
            apps: [{type: "lamp", name: "default_app"}]
        services:
          default: {}
        storage_access:
          default_app_uploads:
            readable: true
            writeable: true

  - name: static-app
    driver:
      network:
        - ["private_network", {ip: "10.10.10.103"}]
    run_list:
      - recipe[core::static_app_server]
      - recipe[core::deployment]
      - recipe[core::firewall]
    attributes:
      core:
        apps:
          default_assets:
            type: static
            moniker: assets
            service: default
            storage:
              default_app_uploads:
                path: uploads
                options: ro
        deployments:
          app_default:
            apps: [{type: "static", name: "default_assets"}]
        services:
          default: {}
        storage_access:
          default_app_uploads:
            readable: true
      ssl:
        domain: 'example_com'
