AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Guardfile
    - Rakefile
    - Thorfile

Style/LineLength:
  Max: 95

Style/RegexpLiteral:
  Exclude:
    - Guardfile

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - metadata.rb

Style/SpaceInsideHashLiteralBraces:
  Enabled: false
