name             'otr'
maintainer       'OurTownRentals.com'
maintainer_email 'evan@ourtownrentals.com'
license          'All rights reserved'
description      'Core infrastructure for OurTownRentals.com.'
version          '0.0.0'

depends 'apt', '~> 2.4.0'
depends 'chef-sugar', '~> 2.0.0'
depends 'firewall', '~> 0.11.8'
depends 'ntp', '~> 1.6.2'
depends 'oh-my-zsh', '~> 0.4.3'
depends 'openssh', '~> 1.3.4'
depends 'sudo', '~> 2.6.0'
depends 'timezone-ii', '~> 0.2.0'
depends 'users', '~> 1.7.0'
depends 'vim', '~> 1.1.2'
depends 'zsh', '~> 1.0.0'
